name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t garghitesh1905/wisecow:latest .

    - name: Set up Kind
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: v0.17.0
        
    - name: Delete existing Kind cluster (if any)
      run: kind delete cluster || true

    - name: Create Kind cluster
      run: kind create cluster --wait 60s

    - name: Load image into Kind
      run: kind load docker-image garghitesh1905/wisecow:latest

    - name: Apply Kubernetes manifests
      run:  kubectl apply -f k8s-manifests/core 
