name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false  
        tags: garghitesh1905/wisecow:latest

    - name: Set up Kind
      uses: engineerd/setup-kind@v0.5.0

    - name: Load image into Kind cluster
      run: kind load docker-image garghitesh1905/wisecow:latest

    - name: Apply Kubernetes manifests
      run: kubectl apply -f k8s-manifests/
